server:
  port: 9090
  servlet:
    context-path: /bookshop
  error:
    whitelabel:
      enabled: false
debug: false
spring:
  application:
    name: bookshop
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bookshop
      authentication-database: admin
      uuid-representation: standard
      username: user
      password: secret
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration, org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: secret
    ssl:
      enabled: false