services:

  mongodb:
    image: bitnami/mongodb
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGODB_USERNAME=user
      - MONGODB_PASSWORD=secret
      - MONGODB_DATABASE=bookshop
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ADVERTISED_HOSTNAME=mongodb
      - MONGODB_REPLICA_SET_NAME=replicaset
      - MONGODB_PORT_NUMBER=27017
      - MONGODB_REPLICA_SET_KEY=replicasetkey
      - MONGODB_ROOT_PASSWORD=secret

  rabbit:
    image: bitnami/rabbitmq
    container_name: rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_USERNAME=user
      - RABBITMQ_PASSWORD=secret
